### ISSUE TITLE
Install prettier and run every pre-commit. Might be better to install into code editor also to run prettier every save.

### ISSUE THREAD

**Issue by miguelvalencia2497** [kurtvalera/react-pokemon-kurt#1]
Code formatting seems to be over the place. Let's fix it with prettier. 

Referencing link to prettier below.
https://prettier.io/docs/en/install.html

Prettier can be used with a pre-commit too to re-format your files that are marked as “staged” via git add before you commit. 

Referencing a few options below. Up to you which one you want to use.

- [lint-staged](https://github.com/okonet/lint-staged)
- [pretty-quick](https://github.com/azz/pretty-quick)
- [pre-commit](https://github.com/pre-commit/pre-commit)

Some of these are used in conjunction with [husky](https://github.com/typicode/husky). Check if the package you choose needs husky to be installed.

**Comment by kurtvalera** [comment]
[Prettier Setup](https://github.com/kurtvalera/react-pokemon-kurt/pull/2)
