### ISSUE TITLE
Remove console logs and irrelevant comments

### ISSUE THREAD

**Issue by miguelvalencia2497** [kurtvalera/react-pokemon-kurt#3]
`console.logs` in code show even after a project is deployed in a test/production server. It's always a good practice to remove `console.logs` before committing changes.

For now let's remove existing `console.logs` in the code. Let's remove unnecessary comments too.

**Comment by kurtvalera** [comment]
Cannot create a pull request for this issue. [Removed console logs branch](https://github.com/kurtvalera/react-pokemon-kurt/tree/task/3/-remove-console-logs)
